


export default {
    LOAD_SETTINGS: "LOAD_SETTINGS",
    SAVE_SETTINGS: "SAVE_SETTINGS",

    SET_FOLDER: "SET_FOLDER",

    CLOSE_WINDOW: "CLOSE_WINDOW",

    WORKER: "WORKER",
    WORKER_RESPONSE: "WORKER_RESPONSE"
};
